-- MySQL Script generated by MySQL Workbench
-- Thu Aug 29 10:09:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
    'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema base
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `base`;

-- -----------------------------------------------------
-- Schema base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base` DEFAULT CHARACTER SET utf8;
USE `base`;

-- -----------------------------------------------------
-- Table `base`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`comment`;

CREATE TABLE IF NOT EXISTS `base`.`comment`
(
    `id`          INT UNSIGNED        NOT NULL AUTO_INCREMENT,
    `comment_id`  INT UNSIGNED        NULL,
    `resource`    VARCHAR(255)        NOT NULL,
    `resource_id` INT UNSIGNED        NOT NULL,
    `person`      VARCHAR(255)        NOT NULL,
    `person_id`   INT                 NOT NULL,
    `status`      TINYINT(1) UNSIGNED NULL     DEFAULT 0,
    `is_viewed`   TINYINT             NULL     DEFAULT 0,
    `level`       SMALLINT UNSIGNED   NOT NULL DEFAULT 1,
    `path`        VARCHAR(500)        NULL     DEFAULT NULL,
    `text`        TEXT                NOT NULL,
    `created_at`  TIMESTAMP           NULL     DEFAULT NULL,
    `updated_at`  TIMESTAMP           NULL     DEFAULT NULL,
    `deleted_at`  TIMESTAMP           NULL     DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `resource` (`resource` ASC),
    INDEX `resource_id` (`resource_id` ASC),
    INDEX `person` (`person` ASC),
    INDEX `person_id` (`person_id` ASC),
    INDEX `path` (`path` ASC),
    INDEX `fk_comment_comment1_idx` (`comment_id` ASC),
    CONSTRAINT `fk_comment_comment1`
        FOREIGN KEY (`comment_id`)
            REFERENCES `base`.`comment` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`currency`;

CREATE TABLE IF NOT EXISTS `base`.`currency`
(
    `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `global_id`  VARCHAR(50)  NOT NULL,
    `num_code`   INT          NOT NULL,
    `char_code`  VARCHAR(45)  NOT NULL,
    `title`      VARCHAR(500) NOT NULL,
    `created_at` TIMESTAMP    NULL DEFAULT NULL,
    `updated_at` TIMESTAMP    NULL DEFAULT NULL,
    `deleted_at` TIMESTAMP    NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    UNIQUE INDEX `num_code_UNIQUE` (`num_code` ASC),
    UNIQUE INDEX `char_code_UNIQUE` (`char_code` ASC),
    UNIQUE INDEX `global_id_UNIQUE` (`global_id` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`currency_exchange_rate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`currency_exchange_rate`;

CREATE TABLE IF NOT EXISTS `base`.`currency_exchange_rate`
(
    `id`          INT UNSIGNED   NOT NULL AUTO_INCREMENT,
    `currency_id` INT UNSIGNED   NOT NULL,
    `value`       DECIMAL(10, 4) NOT NULL,
    `date_rate`   TIMESTAMP      NOT NULL,
    `created_at`  TIMESTAMP      NULL DEFAULT NULL,
    `updated_at`  TIMESTAMP      NULL DEFAULT NULL,
    `deleted_at`  TIMESTAMP      NULL DEFAULT NULL,
    PRIMARY KEY (`id`, `currency_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_currency_exchange_rate_currency1_idx` (`currency_id` ASC),
    CONSTRAINT `fk_currency_exchange_rate_currency1`
        FOREIGN KEY (`currency_id`)
            REFERENCES `base`.`currency` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`gallery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`gallery`;

CREATE TABLE IF NOT EXISTS `base`.`gallery`
(
    `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `title`       VARCHAR(255) NULL DEFAULT NULL,
    `description` TEXT         NULL DEFAULT NULL,
    `sort`        INT          NULL DEFAULT 0,
    `image`       VARCHAR(500) NULL DEFAULT NULL,
    `url`         VARCHAR(255) NULL DEFAULT NULL,
    `created_at`  TIMESTAMP    NULL DEFAULT NULL,
    `updated_at`  TIMESTAMP    NULL DEFAULT NULL,
    `deleted_at`  TIMESTAMP    NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`gallery_has_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`gallery_has_resource`;

CREATE TABLE IF NOT EXISTS `base`.`gallery_has_resource`
(
    `gallery_id`  INT UNSIGNED NOT NULL,
    `resource`    VARCHAR(255) NOT NULL,
    `resource_id` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`gallery_id`, `resource`, `resource_id`),
    INDEX `fk_gallery_has_resource_gallery1_idx` (`gallery_id` ASC),
    CONSTRAINT `fk_gallery_has_resource_gallery1`
        FOREIGN KEY (`gallery_id`)
            REFERENCES `base`.`gallery` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base`.`gallery_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`gallery_image`;

CREATE TABLE IF NOT EXISTS `base`.`gallery_image`
(
    `id`            INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `gallery_id`    INT UNSIGNED NULL,
    `original_name` VARCHAR(255) NOT NULL,
    `image`         VARCHAR(255) NOT NULL,
    `title`         VARCHAR(255) NULL DEFAULT NULL,
    `description`   TEXT         NULL DEFAULT NULL,
    `sort`          INT          NULL DEFAULT 0,
    `created_at`    TIMESTAMP    NULL DEFAULT NULL,
    `updated_at`    TIMESTAMP    NULL DEFAULT NULL,
    `deleted_at`    TIMESTAMP    NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    UNIQUE INDEX `href_UNIQUE` (`image` ASC),
    INDEX `fk_gallery_image_gallery1_idx` (`gallery_id` ASC),
    CONSTRAINT `fk_gallery_image_gallery1`
        FOREIGN KEY (`gallery_id`)
            REFERENCES `base`.`gallery` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`history`;

CREATE TABLE IF NOT EXISTS `base`.`history`
(
    `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id`     INT UNSIGNED NULL,
    `ip_id`       INT UNSIGNED NULL,
    `resource`    VARCHAR(255) NOT NULL,
    `resource_id` INT UNSIGNED NOT NULL,
    `event`       VARCHAR(255) NOT NULL DEFAULT 'created',
    `body`        TEXT         NULL     DEFAULT NULL,
    `description` TEXT         NULL     DEFAULT NULL,
    `created_at`  TIMESTAMP    NULL     DEFAULT NULL,
    `updated_at`  TIMESTAMP    NULL     DEFAULT NULL,
    `deleted_at`  TIMESTAMP    NULL     DEFAULT NULL,
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    PRIMARY KEY (`id`),
    INDEX `fk_history_user1_idx` (`user_id` ASC),
    INDEX `fk_history_ip1_idx` (`ip_id` ASC),
    CONSTRAINT `fk_history_user1`
        FOREIGN KEY (`user_id`)
            REFERENCES `base`.`user` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `fk_history_ip1`
        FOREIGN KEY (`ip_id`)
            REFERENCES `base`.`ip` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`info_block`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`info_block`;

CREATE TABLE IF NOT EXISTS `base`.`info_block`
(
    `id`                INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `position`          VARCHAR(45)      NOT NULL,
    `sort`              INT              NULL DEFAULT 0,
    `title`             VARCHAR(255)     NOT NULL,
    `title_short`       VARCHAR(155)     NULL DEFAULT NULL,
    `description_short` TEXT             NULL DEFAULT NULL,
    `description`       TEXT             NULL DEFAULT NULL,
    `make_watermark`    TINYINT UNSIGNED NULL DEFAULT 1,
    `media`             VARCHAR(255)     NULL DEFAULT NULL,
    `image`             VARCHAR(255)     NULL DEFAULT NULL,
    `created_at`        TIMESTAMP        NULL DEFAULT NULL,
    `updated_at`        TIMESTAMP        NULL DEFAULT NULL,
    `deleted_at`        TIMESTAMP        NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `title` (`title` ASC)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base`.`info_block_has_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`info_block_has_resource`;

CREATE TABLE IF NOT EXISTS `base`.`info_block_has_resource`
(
    `resource_id`   INT UNSIGNED NOT NULL,
    `resource`      VARCHAR(255) NOT NULL,
    `info_block_id` INT UNSIGNED NOT NULL,
    INDEX `info_block_has_resource_info_block_id` (`info_block_id` ASC),
    INDEX `info_block_has_resource_resource_id` (`resource_id` ASC),
    INDEX `info_block_has_resource_resource` (`resource` ASC),
    CONSTRAINT `fk_info_block_has_resource_info_block1`
        FOREIGN KEY (`info_block_id`)
            REFERENCES `base`.`info_block` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base`.`info_block_language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`info_block_language`;

CREATE TABLE IF NOT EXISTS `base`.`info_block_language`
(
    `id`                  INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `info_block_id`       INT UNSIGNED NOT NULL,
    `language`            VARCHAR(45)  NOT NULL,
    `title`               VARCHAR(255) NOT NULL,
    `title_short`         VARCHAR(155) NULL DEFAULT NULL,
    `preview_description` TEXT         NULL DEFAULT NULL,
    `description`         TEXT         NULL DEFAULT NULL,
    PRIMARY KEY (`id`, `info_block_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `title` (`title` ASC),
    INDEX `fk_info_block_language_info_block1_idx` (`info_block_id` ASC),
    CONSTRAINT `fk_info_block_language_info_block1`
        FOREIGN KEY (`info_block_id`)
            REFERENCES `base`.`info_block` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base`.`ip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`ip`;

CREATE TABLE IF NOT EXISTS `base`.`ip`
(
    `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ip`         VARCHAR(255) NOT NULL,
    `status`     TINYINT(1)   NULL DEFAULT 1,
    `created_at` TIMESTAMP    NULL DEFAULT NULL,
    `updated_at` TIMESTAMP    NULL DEFAULT NULL,
    `deleted_at` TIMESTAMP    NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    UNIQUE INDEX `ip_UNIQUE` (`ip` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`letter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`letter`;

CREATE TABLE IF NOT EXISTS `base`.`letter`
(
    `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `resource`    VARCHAR(255) NOT NULL,
    `resource_id` INT UNSIGNED NOT NULL,
    `person`      VARCHAR(255) NOT NULL,
    `person_id`   INT          NOT NULL,
    `subject`     VARCHAR(255) NULL DEFAULT NULL,
    `text`        TEXT         NULL DEFAULT NULL,
    `is_viewed`   TINYINT      NULL DEFAULT 0,
    `created_at`  TIMESTAMP    NULL DEFAULT NULL,
    `updated_at`  TIMESTAMP    NULL DEFAULT NULL,
    `deleted_at`  TIMESTAMP    NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`menu`;

CREATE TABLE IF NOT EXISTS `base`.`menu`
(
    `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `title`       VARCHAR(255) NOT NULL,
    `name`        VARCHAR(45)  NOT NULL,
    `description` VARCHAR(255) NULL DEFAULT NULL,
    `created_at`  TIMESTAMP    NULL DEFAULT NULL,
    `updated_at`  TIMESTAMP    NULL DEFAULT NULL,
    `deleted_at`  TIMESTAMP    NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    UNIQUE INDEX `title_UNIQUE` (`title` ASC),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`menu_has_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`menu_has_resource`;

CREATE TABLE IF NOT EXISTS `base`.`menu_has_resource`
(
    `menu_id`     INT UNSIGNED NOT NULL,
    `resource`    VARCHAR(255) NOT NULL,
    `resource_id` INT UNSIGNED NOT NULL,
    INDEX `fk_menu_has_resource_menu1_idx` (`menu_id` ASC),
    PRIMARY KEY (`menu_id`, `resource`, `resource_id`),
    CONSTRAINT `fk_menu_has_resource_menu1`
        FOREIGN KEY (`menu_id`)
            REFERENCES `base`.`menu` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`menu_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`menu_item`;

CREATE TABLE IF NOT EXISTS `base`.`menu_item`
(
    `id`           INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `menu_id`      INT UNSIGNED NOT NULL,
    `menu_item_id` INT UNSIGNED NULL,
    `resource`     VARCHAR(255) NULL DEFAULT NULL,
    `resource_id`  INT UNSIGNED NULL DEFAULT NULL,
    `title`        VARCHAR(255) NOT NULL,
    `sort`         INT          NULL DEFAULT 0,
    `url`          VARCHAR(255) NOT NULL,
    `created_at`   TIMESTAMP    NULL DEFAULT NULL,
    `updated_at`   TIMESTAMP    NULL DEFAULT NULL,
    `deleted_at`   TIMESTAMP    NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_menu_item_menu1_idx` (`menu_id` ASC),
    INDEX `fk_menu_item_menu_item1_idx` (`menu_item_id` ASC),
    CONSTRAINT `fk_menu_item_menu1`
        FOREIGN KEY (`menu_id`)
            REFERENCES `base`.`menu` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `fk_menu_item_menu_item1`
        FOREIGN KEY (`menu_item_id`)
            REFERENCES `base`.`menu_item` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`menu_item_language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`menu_item_language`;

CREATE TABLE IF NOT EXISTS `base`.`menu_item_language`
(
    `id`           INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `title`        VARCHAR(255) NOT NULL,
    `language`     VARCHAR(45)  NOT NULL,
    `menu_item_id` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`id`, `menu_item_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_menu_item_language_menu_item1_idx` (`menu_item_id` ASC),
    CONSTRAINT `fk_menu_item_language_menu_item1`
        FOREIGN KEY (`menu_item_id`)
            REFERENCES `base`.`menu_item` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`migrations`;

CREATE TABLE IF NOT EXISTS `base`.`migrations`
(
    `id`        INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `migration` VARCHAR(255) NOT NULL,
    `batch`     INT          NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`post`;

CREATE TABLE IF NOT EXISTS `base`.`post`
(
    `id`                  INT UNSIGNED         NOT NULL AUTO_INCREMENT,
    `template_id`         INT UNSIGNED         NULL,
    `post_category_id`    INT UNSIGNED         NULL,
    `meta_title`          VARCHAR(100)         NULL DEFAULT NULL,
    `meta_description`    VARCHAR(200)         NULL DEFAULT NULL,
    `alias`               VARCHAR(255)         NOT NULL,
    `url`                 VARCHAR(1000)        NOT NULL,
    `is_published`        TINYINT UNSIGNED     NULL DEFAULT 1,
    `is_favourites`       TINYINT UNSIGNED     NULL DEFAULT 0,
    `has_comments`        TINYINT UNSIGNED     NULL DEFAULT 0,
    `show_image_post`     TINYINT UNSIGNED     NULL DEFAULT 1,
    `show_image_category` TINYINT UNSIGNED     NULL DEFAULT 1,
    `make_watermark`      TINYINT UNSIGNED     NULL DEFAULT 1,
    `in_sitemap`          TINYINT UNSIGNED     NULL DEFAULT 1,
    `media`               VARCHAR(255)         NULL DEFAULT NULL,
    `title`               VARCHAR(255)         NOT NULL,
    `title_short`         VARCHAR(155)         NULL DEFAULT NULL,
    `description`         TEXT                 NULL DEFAULT NULL,
    `description_short`   TEXT                 NULL DEFAULT NULL,
    `show_date`           TINYINT              NULL DEFAULT 1,
    `date_pub`            TIMESTAMP            NULL DEFAULT NULL,
    `date_end`            TIMESTAMP            NULL DEFAULT NULL,
    `image`               VARCHAR(255)         NULL DEFAULT NULL,
    `hits`                INT UNSIGNED         NULL DEFAULT 0,
    `sort`                INT                  NULL DEFAULT 0,
    `stars`               FLOAT(1, 1) UNSIGNED NULL DEFAULT 0.0,
    `created_at`          TIMESTAMP            NULL DEFAULT NULL,
    `updated_at`          TIMESTAMP            NULL DEFAULT NULL,
    `deleted_at`          TIMESTAMP            NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `title` (`title` ASC),
    INDEX `fk_post_render1_idx` (`template_id` ASC),
    INDEX `fk_post_post_category1_idx` (`post_category_id` ASC),
    UNIQUE INDEX `alias_UNIQUE` (`alias` ASC),
    UNIQUE INDEX `url_UNIQUE` (`url` ASC),
    CONSTRAINT `fk_post_render1`
        FOREIGN KEY (`template_id`)
            REFERENCES `base`.`template` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `fk_post_post_category1`
        FOREIGN KEY (`post_category_id`)
            REFERENCES `base`.`post_category` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base`.`post_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`post_category`;

CREATE TABLE IF NOT EXISTS `base`.`post_category`
(
    `id`                  INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `template_id`         INT UNSIGNED     NULL,
    `post_category_id`    INT UNSIGNED     NULL,
    `meta_title`          VARCHAR(100)     NULL DEFAULT NULL,
    `meta_description`    VARCHAR(200)     NULL DEFAULT NULL,
    `alias`               VARCHAR(255)     NOT NULL,
    `url`                 VARCHAR(1000)    NOT NULL,
    `is_published`        TINYINT UNSIGNED NULL DEFAULT 1,
    `is_favourites`       TINYINT UNSIGNED NULL DEFAULT 0,
    `make_watermark`      TINYINT UNSIGNED NULL DEFAULT 1,
    `in_sitemap`          TINYINT UNSIGNED NULL DEFAULT 1,
    `image`               VARCHAR(255)     NULL DEFAULT NULL,
    `show_image`          TINYINT UNSIGNED NULL DEFAULT 1,
    `title`               VARCHAR(255)     NOT NULL,
    `title_short`         VARCHAR(150)     NULL DEFAULT NULL,
    `description`         TEXT             NULL DEFAULT NULL,
    `preview_description` TEXT             NULL DEFAULT NULL,
    `sort`                INT UNSIGNED     NULL DEFAULT 0,
    `created_at`          TIMESTAMP        NULL DEFAULT NULL,
    `updated_at`          TIMESTAMP        NULL DEFAULT NULL,
    `deleted_at`          TIMESTAMP        NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `title` (`title` ASC),
    INDEX `fk_post_category_render1_idx` (`template_id` ASC),
    INDEX `fk_post_category_post_category1_idx` (`post_category_id` ASC),
    UNIQUE INDEX `alias_UNIQUE` (`alias` ASC),
    UNIQUE INDEX `url_UNIQUE` (`url` ASC),
    CONSTRAINT `fk_post_category_render1`
        FOREIGN KEY (`template_id`)
            REFERENCES `base`.`template` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `fk_post_category_post_category1`
        FOREIGN KEY (`post_category_id`)
            REFERENCES `base`.`post_category` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base`.`post_category_language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`post_category_language`;

CREATE TABLE IF NOT EXISTS `base`.`post_category_language`
(
    `id`                  INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `post_category_id`    INT UNSIGNED NOT NULL,
    `meta_title`          VARCHAR(100) NULL DEFAULT NULL,
    `meta_description`    VARCHAR(200) NULL DEFAULT NULL,
    `language`            VARCHAR(45)  NOT NULL,
    `title`               VARCHAR(255) NOT NULL,
    `title_short`         VARCHAR(150) NULL DEFAULT NULL,
    `description`         TEXT         NULL DEFAULT NULL,
    `preview_description` TEXT         NULL DEFAULT NULL,
    PRIMARY KEY (`id`, `post_category_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `title` (`title` ASC),
    INDEX `fk_post_category_language_post_category1_idx` (`post_category_id` ASC),
    CONSTRAINT `fk_post_category_language_post_category1`
        FOREIGN KEY (`post_category_id`)
            REFERENCES `base`.`post_category` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base`.`post_language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`post_language`;

CREATE TABLE IF NOT EXISTS `base`.`post_language`
(
    `id`                  INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `post_id`             INT UNSIGNED NOT NULL,
    `meta_title`          VARCHAR(100) NULL DEFAULT NULL,
    `meta_description`    VARCHAR(200) NULL DEFAULT NULL,
    `language`            VARCHAR(45)  NOT NULL,
    `title`               VARCHAR(255) NOT NULL,
    `title_short`         VARCHAR(155) NULL DEFAULT NULL,
    `preview_description` TEXT         NULL DEFAULT NULL,
    `description`         TEXT         NULL DEFAULT NULL,
    PRIMARY KEY (`id`, `post_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `title` (`title` ASC),
    INDEX `fk_post_language_post1_idx` (`post_id` ASC),
    CONSTRAINT `fk_post_language_post1`
        FOREIGN KEY (`post_id`)
            REFERENCES `base`.`post` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base`.`redirect`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`redirect`;

CREATE TABLE IF NOT EXISTS `base`.`redirect`
(
    `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `url`        VARCHAR(500) NOT NULL,
    `url_old`    VARCHAR(500) NOT NULL,
    `created_at` TIMESTAMP    NULL DEFAULT NULL,
    `updated_at` TIMESTAMP    NULL DEFAULT NULL,
    `deleted_at` TIMESTAMP    NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    UNIQUE INDEX `url_old_UNIQUE` (`url_old` ASC),
    UNIQUE INDEX `url_UNIQUE` (`url` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`setting`;

CREATE TABLE IF NOT EXISTS `base`.`setting`
(
    `id`           INT UNSIGNED  NOT NULL AUTO_INCREMENT,
    `key`          VARCHAR(45)   NOT NULL,
    `title`        VARCHAR(100)  NOT NULL,
    `description`  TEXT          NULL DEFAULT NULL,
    `value_string` VARCHAR(1000) NULL DEFAULT NULL,
    `value_text`   LONGTEXT      NULL DEFAULT NULL,
    `value_json`   TEXT          NULL DEFAULT NULL,
    `value_bool`   SMALLINT      NULL DEFAULT 0,
    `created_at`   TIMESTAMP     NULL DEFAULT NULL,
    `updated_at`   TIMESTAMP     NULL DEFAULT NULL,
    `deleted_at`   TIMESTAMP     NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `key_UNIQUE` (`key` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`tag`;

CREATE TABLE IF NOT EXISTS `base`.`tag`
(
    `id`               INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `meta_title`       VARCHAR(100)     NULL DEFAULT NULL,
    `meta_description` VARCHAR(200)     NULL DEFAULT NULL,
    `in_sitemap`       TINYINT          NULL DEFAULT 1,
    `is_published`     TINYINT UNSIGNED NULL DEFAULT 1,
    `is_favourites`    TINYINT UNSIGNED NULL DEFAULT 0,
    `make_watermark`   TINYINT          NULL DEFAULT 1,
    `image`            VARCHAR(255)     NULL DEFAULT NULL,
    `show_image`       TINYINT          NULL DEFAULT 1,
    `title`            VARCHAR(255)     NOT NULL,
    `title_short`      VARCHAR(150)     NULL DEFAULT NULL,
    `description`      TEXT             NULL DEFAULT NULL,
    `sort`             INT UNSIGNED     NULL DEFAULT 0,
    `created_at`       TIMESTAMP        NULL DEFAULT NULL,
    `updated_at`       TIMESTAMP        NULL DEFAULT NULL,
    `deleted_at`       TIMESTAMP        NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    UNIQUE INDEX `title_UNIQUE` (`title` ASC)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base`.`tag_has_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`tag_has_resource`;

CREATE TABLE IF NOT EXISTS `base`.`tag_has_resource`
(
    `tag_id`      INT UNSIGNED NOT NULL,
    `resource`    VARCHAR(255) NOT NULL,
    `resource_id` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`tag_id`, `resource`, `resource_id`),
    CONSTRAINT `fk_tag_has_resource_tag1`
        FOREIGN KEY (`tag_id`)
            REFERENCES `base`.`tag` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base`.`tag_language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`tag_language`;

CREATE TABLE IF NOT EXISTS `base`.`tag_language`
(
    `id`               INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `tag_id`           INT UNSIGNED NOT NULL,
    `meta_title`       VARCHAR(100) NULL DEFAULT NULL,
    `meta_description` VARCHAR(200) NULL DEFAULT NULL,
    `language`         VARCHAR(45)  NOT NULL,
    `title`            VARCHAR(255) NOT NULL,
    `title_short`      VARCHAR(150) NULL DEFAULT NULL,
    `description`      TEXT         NULL DEFAULT NULL,
    PRIMARY KEY (`id`, `tag_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    UNIQUE INDEX `title_UNIQUE` (`title` ASC),
    INDEX `fk_tag_language_tag1_idx` (`tag_id` ASC),
    CONSTRAINT `fk_tag_language_tag1`
        FOREIGN KEY (`tag_id`)
            REFERENCES `base`.`tag` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base`.`telegram_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`telegram_message`;

CREATE TABLE IF NOT EXISTS `base`.`telegram_message`
(
    `id`                  INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `telegram_message_id` INT UNSIGNED NULL,
    `telegram_user_id`    INT UNSIGNED NULL,
    `message_id`          INT UNSIGNED NOT NULL,
    `update_id`           INT UNSIGNED NULL DEFAULT NULL,
    `text`                TEXT         NULL DEFAULT NULL,
    `search`              TEXT         NULL DEFAULT NULL,
    `date`                INT UNSIGNED NULL DEFAULT NULL,
    `created_at`          TIMESTAMP    NULL DEFAULT NULL,
    `updated_at`          TIMESTAMP    NULL DEFAULT NULL,
    `deleted_at`          TIMESTAMP    NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    FULLTEXT INDEX `search` (`search`),
    INDEX `fk_telegram_message_telegram_message1_idx` (`telegram_message_id` ASC),
    INDEX `fk_telegram_message_telegram_user1_idx` (`telegram_user_id` ASC),
    CONSTRAINT `fk_telegram_message_telegram_message1`
        FOREIGN KEY (`telegram_message_id`)
            REFERENCES `base`.`telegram_message` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `fk_telegram_message_telegram_user1`
        FOREIGN KEY (`telegram_user_id`)
            REFERENCES `base`.`telegram_user` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`telegram_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`telegram_user`;

CREATE TABLE IF NOT EXISTS `base`.`telegram_user`
(
    `id`            INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id`       INT UNSIGNED NULL,
    `first_name`    VARCHAR(500) NULL DEFAULT NULL,
    `last_name`     VARCHAR(500) NULL DEFAULT NULL,
    `username`      VARCHAR(500) NULL DEFAULT NULL,
    `type`          VARCHAR(500) NULL DEFAULT NULL,
    `language_code` VARCHAR(10)  NULL DEFAULT NULL,
    `created_at`    TIMESTAMP    NULL DEFAULT NULL,
    `updated_at`    TIMESTAMP    NULL DEFAULT NULL,
    `deleted_at`    TIMESTAMP    NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_telegram_user_user1_idx` (`user_id` ASC),
    CONSTRAINT `fk_telegram_user_user1`
        FOREIGN KEY (`user_id`)
            REFERENCES `base`.`user` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`template`;

CREATE TABLE IF NOT EXISTS `base`.`template`
(
    `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `title`      VARCHAR(255) NOT NULL,
    `name`       VARCHAR(45)  NOT NULL,
    `resource`   VARCHAR(255) NULL DEFAULT NULL,
    `created_at` TIMESTAMP    NULL DEFAULT NULL,
    `updated_at` TIMESTAMP    NULL DEFAULT NULL,
    `deleted_at` TIMESTAMP    NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`user`;

CREATE TABLE IF NOT EXISTS `base`.`user`
(
    `id`                   INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `first_name`           VARCHAR(255)     NOT NULL DEFAULT 'Undefined',
    `last_name`            VARCHAR(255)     NOT NULL DEFAULT 'Undefined',
    `patronymic`           VARCHAR(255)     NULL     DEFAULT NULL,
    `phone`                VARCHAR(255)     NULL     DEFAULT NULL,
    `email`                VARCHAR(255)     NOT NULL,
    `is_email`             TINYINT UNSIGNED NULL     DEFAULT 0,
    `is_phone`             TINYINT UNSIGNED NULL     DEFAULT 0,
    `status`               SMALLINT         NOT NULL DEFAULT 0,
    `avatar`               VARCHAR(255)     NULL     DEFAULT NULL,
    `password_hash`        VARCHAR(255)     NOT NULL,
    `remember_token`       VARCHAR(500)     NULL     DEFAULT NULL,
    `auth_token`           VARCHAR(500)     NULL     DEFAULT NULL,
    `auth_key`             VARCHAR(32)      NULL     DEFAULT NULL,
    `password_reset_token` VARCHAR(255)     NULL     DEFAULT NULL,
    `created_at`           TIMESTAMP        NULL     DEFAULT NULL,
    `updated_at`           TIMESTAMP        NULL     DEFAULT NULL,
    `deleted_at`           TIMESTAMP        NULL     DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `email` (`email` ASC),
    UNIQUE INDEX `password_reset_token` (`password_reset_token` ASC),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
    INDEX `first_name` (`first_name` ASC),
    INDEX `last_name` (`last_name` ASC)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `base`.`user_guest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`user_guest`;

CREATE TABLE IF NOT EXISTS `base`.`user_guest`
(
    `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `email`      VARCHAR(255) NOT NULL,
    `name`       VARCHAR(255) NULL DEFAULT NULL,
    `created_at` TIMESTAMP    NULL DEFAULT NULL,
    `updated_at` TIMESTAMP    NULL DEFAULT NULL,
    `deleted_at` TIMESTAMP    NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`user_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`user_token`;

CREATE TABLE IF NOT EXISTS `base`.`user_token`
(
    `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id`    INT UNSIGNED NULL,
    `type`       VARCHAR(45)  NOT NULL,
    `token`      VARCHAR(300) NOT NULL,
    `created_at` TIMESTAMP    NULL DEFAULT NULL,
    `updated_at` TIMESTAMP    NULL DEFAULT NULL,
    `deleted_at` TIMESTAMP    NULL DEFAULT NULL,
    `expired_at` TIMESTAMP    NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_user_token_user1_idx` (`user_id` ASC),
    UNIQUE INDEX `token_UNIQUE` (`token` ASC),
    CONSTRAINT `fk_user_token_user1`
        FOREIGN KEY (`user_id`)
            REFERENCES `base`.`user` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
